// test
export const SET_INVENTORY_TYPE = "SET_INVENTORY_TYPE";
export const SET_INVENTORY_TYPE_SUCCESS = "SET_INVENTORY_TYPE_SUCCESS";
export const SET_INVENTORY_TYPE_FAIL = "SET_INVENTORY_TYPE_FAIL";
